version: "3.8"

services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elastic-search
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elastic-search:9200
      ELASTICSEARCH_HOSTS: '["http://elastic-search:9200"]'

  stock-analyzer:
    image: custom-stock-analyzer
    container_name: stock-analyzer
    build: .
    depends_on:
      - elastic-search
    restart: on-failure
    ports:
      - "8088:8088"
      - "5005:5005"
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}

volumes:
  es-volume: