version: "3.8"

services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elastic-search
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
      ELASTIC_PASSWORD: password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
     ELASTICSEARCH_URL : http://elastic-search:9200
     ELASTICSEARCH_HOSTS : '["http://elastic-search:9200"]'
     ELASTICSEARCH_USERNAME : username
     ELASTICSEARCH_PASSWORD : password

  stock-analyzer:
    image: custom-stock-analyzer
    container_name: stock-analyzer
    build: .
    depends_on:
      - elastic-search
    restart: on-failure
    ports:
      - "8088:8088"
      - "5005:5005"
    environment:
      FINNHUB_API_KEY : ${FINNHUB_API_KEY}
      ELASTIC_SEARCH : elastic-search
      ELASTIC_SEARCH_PORT : 9200
      ES_USERNAME: username
      ES_PASSWORD: password

volumes:
  es-volume: