version: "3.8"

services:
  #Ktor Stock Analyzer
  stock-database:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "stockdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ROOT_PASSWORD: "rootpass"
    ports:
    - "5432:5432"

  stock-analyzer:
    image: custom-stock-analyzer
    container_name: stock-analyzer
    build: .
    depends_on:
      - stock-database
    restart: on-failure
    ports:
      - "8088:8088"

