version: "3.8"

services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elastic-search
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  stock-database:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "stockdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ROOT_PASSWORD: "rootpass"
    ports:
      - "5432:5432"

  stock-analyzer:
    image: custom-stock-analyzer
    container_name: stock-analyzer
    build: .
    depends_on:
      - stock-database
      - elastic-search
    restart: on-failure
    ports:
      - "8088:8088"
      - "5005:5005"
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}

volumes:
  es-volume: