version: "3.9"

services:

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass redisDockerTestPassword

  stock-fetcher:
    container_name: stock-fetcher
    build:
      context: .
    depends_on:
      - redis
    restart: on-failure
    ports:
      - "8088:8088"
      - "5005:5005"
    environment:
      FINNHUB_API_KEY : ${FINNHUB_API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: redisDockerTestPassword

networks:
  default:
    name: compose_network
    external: true

volumes:
  redis-volume:
    driver: local