apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: stockcomp-client-backend-image
      jib: {}

manifests:
  rawYaml:
    - k8s/app-config.yaml
    - k8s/stockcomp-client-backend.yaml
