apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: stockanalyzer-image
      jib: {}

manifests:
  rawYaml:
    - k8s/redis.yaml
    - k8s/app-config.yaml
    - k8s/stock-analyzer.yaml
