apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: stockcomp-client-backend-image
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/config-map-client-backend.yaml
    - k8s/stockcomp-client-backend.yaml
