apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.8-alpine
          volumeMounts:
            - mountPath: /data
              name: redis-persistent-storage
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
