apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer
  labels:
    app: stock-analyzer
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 31000
  selector:
    app : stock-analyzer