apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-analyzer
  template:
    metadata:
      labels:
        app: stock-analyzer
    spec:
      containers:
        - name: stock-analyzer
          image: ghcr.io/andrewass/stock-analyzer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
