apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql-service
spec:
  ports:
    - port: 5432
      name: postgresql-port
  clusterIP: None
  selector:
    app: postgresql-service
