apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: el-search
spec:
  version: 7.14.1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false