apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-analyzer
  template:
    metadata:
      labels:
        app: stock-analyzer
    spec:
      containers:
        - name: stock-analyzer
          image: ghcr.io/andrewass/stock-analyzer:latest
          ports:
            - containerPort: 8088
          env:
            - name: ELASTIC_SEARCH
              value: elasticsearch-es-http
            - name: ELASTIC_SEARCH_PORT
              value: "9200"
            - name: ES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config-sa
                  key: es_username
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
            - name: FINNHUB_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: config-sa
                  key: finnhub_api_key

---

apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer-service
  labels:
    app: stock-analyzer
spec:
  selector:
    app: stock-analyzer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
