apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-analyzer
  template:
    metadata:
      labels:
        app: stock-analyzer
    spec:
      containers:
        - name: stock-analyzer
          image: ghcr.io/andrewass/stock-analyzer:latest
          ports:
            - containerPort: 8088
          env:
          - name: ELASTIC_SEARCH
            value: elasticsearch-es-http
          - name: ELASTIC_SEARCH_PORT
            value: "9200"

---

apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer-service
  labels:
    app: stock-analyzer
spec:
  selector:
    app: stock-analyzer
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30001

